Fix invalid param value "use_gpu":"true" (#383)
After installing latest Jupyter notebooke, the json format check is strick, due to passing a string value "true"

for the "use_gpu":"true", "use_gpu": True is required.

```
params = {
    "tree_method": "gpu_hist",
    "grow_policy": "depthwise",
    "num_workers": 1,
    "use_gpu": "true",
}
```
TypeError: Invalid param value given for param "use_gpu".

Boolean Param requires value of type bool. Found <class 'str'>.

More over, "use_gpu": True is deprecated in dmlc/XGBoost, change to user "device": "cuda" instead

Signed-off-by: Tim Liu <timl@nvidia.com>